spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    continueOnError: true
server:
  port: 8080
  servlet:
    context-path: /
springdoc:
  api-docs:
    path: /api-docs